Repository ComPWA/qrules, pull requests merged in 2021-04, with the labels that each got.

#2 fix: add missing test_parity_prefactor
  tests/unit/test_parity_prefactor.py
Labels: 🔨 Maintenance

#3 docs: remove expertsystem adrs
  .pre-commit-config.yaml
  docs/adr.md
  docs/adr/000.md
  docs/adr/001.md
  docs/adr/001/operators.ipynb
  docs/adr/001/parameter_container.py
  docs/adr/001/sympy.ipynb
  docs/adr/002.md
  docs/adr/002/composition.ipynb
  docs/adr/002/expr.ipynb
  docs/adr/002/function.ipynb
  docs/adr/002/helpers.py
  docs/conf.py
  docs/index.md
Labels: 📝 Docs

#4 fix: link to codacy badge
  README.md
  docs/index.md
Labels: Bug

#36 ci: split ci workflow into sty, docs, and tests
  .github/workflows/ci-docs.yml
  .github/workflows/ci-style.yml
  .github/workflows/ci-tests.yml
Labels: 🖱️ DX

#37 ci: fail RTD on warning
  .readthedocs.yml
  docs/index.md
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.9/requirements-dev.txt
  reqs/3.9/requirements-doc.txt
  reqs/3.9/requirements-sty.txt
  reqs/3.9/requirements-test.txt
  reqs/requirements-sty.in
  reqs/requirements-test.in
Labels: 🖱️ DX

#38 ci: standardize cspell config
  .cspell.json
  .editorconfig
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  .vscode/settings.json
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.9/requirements-dev.txt
  reqs/3.9/requirements-doc.txt
  reqs/3.9/requirements-sty.txt
  reqs/3.9/requirements-test.txt
Labels: 🖱️ DX

#39 build!: move requirements back to setup.cfg
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .constraints/upgrade.sh
  .cspell.json
  .github/workflows/ci-docs.yml
  .github/workflows/ci-style.yml
  .github/workflows/ci-tests.yml
  .github/workflows/linkcheck.yml
  .github/workflows/requirements-cron.yml
  .github/workflows/requirements-pr.yml
  .gitpod.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  .vscode/settings.json
  docs/install.md
  environment.yml
  reqs/.gitignore
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-extras.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-extras.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-extras.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  reqs/3.9/requirements-dev.txt
  reqs/3.9/requirements-doc.txt
  reqs/3.9/requirements-extras.txt
  reqs/3.9/requirements-sty.txt
  reqs/3.9/requirements-test.txt
  reqs/3.9/requirements.txt
  reqs/extract_install_requires.py
  reqs/requirements-dev.in
  reqs/requirements-doc.in
  reqs/requirements-sty.in
  reqs/requirements-test.in
  reqs/upgrade.sh
  setup.cfg
  tox.ini
Labels: 🖱️ DX

#41 test: verify default interaction settings
  src/qrules/default_settings.py
  tests/unit/test_default_settings.py
Labels: 🔨 Maintenance

#42 fix: define testpaths in pytest.ini
  .cspell.json
  .pre-commit-config.yaml
  pytest.ini
  tox.ini
Labels: Bug, 🖱️ DX

#43 refactor: rename default_settings to settings
  src/qrules/__init__.py
  src/qrules/_system_control.py
  src/qrules/settings/__init__.py
  src/qrules/settings/defaults.py
  src/qrules/transition.py
  tests/unit/test_parity_prefactor.py
  tests/unit/test_reaction.py
  tests/unit/test_settings.py
Labels: ⚠️ Interface

#44 docs: improve package description in docs
  .gitpod.yml
  README.md
  docs/conf.py
  docs/index.md
Labels: 📝 Docs

#45 feat: determine domains from ParticleCollection
  src/qrules/__init__.py
  src/qrules/quantum_numbers.py
  src/qrules/settings/__init__.py
  src/qrules/settings/defaults.py
  src/qrules/solving.py
  src/qrules/transition.py
  tests/unit/test_settings.py
Labels: 💡 Feature

#47 refactor: rename to InteractionType
  docs/usage/reaction.ipynb
  src/qrules/__init__.py
  src/qrules/_system_control.py
  src/qrules/settings/__init__.py
  src/qrules/transition.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/test_parity_prefactor.py
  tests/unit/test_reaction.py
  tests/unit/test_settings.py
  tests/unit/test_system_control.py
Labels: ⚠️ Interface

#48 refactor: remove globals for max LS
  src/qrules/__init__.py
  src/qrules/settings/__init__.py
  src/qrules/settings/defaults.py
Labels: ⚠️ Interface

#46 refactor: merge settings.defaults into settings
  src/qrules/__init__.py
  src/qrules/settings.py
  src/qrules/settings/defaults.py
Labels: ⚠️ Interface

#40 feat: extend configuration arguments in facade functions
  src/qrules/__init__.py
  src/qrules/settings.py
  src/qrules/transition.py
Labels: Bug, 💡 Feature

#50 refactor: rename particles argument to particle_db
  docs/usage/particle.ipynb
  src/qrules/__init__.py
  src/qrules/_system_control.py
  src/qrules/combinatorics.py
  src/qrules/io/_dot.py
  src/qrules/settings.py
  src/qrules/transition.py
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/test_combinatorics.py
  tests/unit/test_settings.py
Labels: ⚠️ Interface

#51 style: fix isort after pre-commit update
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .pre-commit-config.yaml
  docs/usage/reaction.ipynb
  docs/usage/visualize.ipynb
Labels: 🖱️ DX

#52 ci: add PR template + gitpod extensions
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .github/pull_request_template.md
  .gitpod.yml
  .pre-commit-config.yaml
  docs/conf.py
  docs/usage/reaction.ipynb
Labels: 🖱️ DX

#53 ci: run notebooks with pytest
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  pytest.ini
  setup.cfg
  tox.ini
Labels: 🖱️ DX
