Repository ComPWA/qrules, pull requests merged in 2021-11, with the labels that each got.

#120 ci: upgrade pinned requirements
  .constraints/py3.10.txt
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .cspell.json
  .flake8
  .pre-commit-config.yaml
  setup.cfg
Labels: 🖱️ DX

#121 docs: link to correct version on Binder/Colab
  docs/conf.py
  docs/index.md
  docs/usage/reaction.ipynb
  tox.ini
Labels: 📝 Docs

#123 ci: update pip constraints and pre-commit config
  .constraints/pin_requirements.py
  .constraints/py3.10.txt
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .github/workflows/ci-docs.yml
  .github/workflows/linkcheck.yml
  .github/workflows/requirements-cron.yml
  .github/workflows/requirements-pr.yml
  .pre-commit-config.yaml
  docs/install.md
Labels: 🖱️ DX

#125 ci: update pip constraints and pre-commit config
  .constraints/py3.10.txt
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .github/workflows/requirements-cron.yml
  .github/workflows/requirements-pr.yml
  .gitpod.yml
  .mypy.ini
  .pre-commit-config.yaml
  .vscode/extensions.json
Labels: 🖱️ DX

#126 feat: allow render_node with strip_spin
  docs/usage/visualize.ipynb
  src/qrules/io/_dot.py
  tests/unit/io/test_dot.py
Labels: 💡 Feature

#124 docs: demonstrate LS-coupling in notebook
  .cspell.json
  docs/usage.ipynb
  docs/usage/ls-coupling.ipynb
  src/qrules/conservation_rules.py
Labels: 📝 Docs

#127 ci: update pip constraints and pre-commit config
  .constraints/py3.10.txt
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .pre-commit-config.yaml
Labels: 🖱️ DX

#128 ci: update pip constraints and pre-commit config
  .constraints/py3.10.txt
  .constraints/py3.6.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .flake8
  .github/workflows/requirements-pr.yml
  .mypy.ini
  .pre-commit-config.yaml
  setup.cfg
  setup.py
  tests/unit/test_quantum_numbers.py
Labels: 🖱️ DX
