Repository ComPWA/qrules, pull requests merged in 2024-10, with the labels that each got.

#291 MAINT: drop Python 3.7 & 3.8 support due to EOL
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  docs/conf.py
  pyproject.toml
  src/qrules/__init__.py
  src/qrules/argument_handling.py
  src/qrules/combinatorics.py
  src/qrules/conservation_rules.py
  src/qrules/io/_dot.py
  src/qrules/particle.py
  src/qrules/quantum_numbers.py
  src/qrules/settings.py
  src/qrules/solving.py
  src/qrules/system_control.py
  src/qrules/topology.py
  src/qrules/transition.py
  tests/conftest.py
  tests/unit/conservation_rules/test_clebsch_gordan.py
  tests/unit/conservation_rules/test_spin.py
  tests/unit/test_particle.py
  tests/unit/test_system_control.py
Labels: 🔨 Maintenance

#295 FIX: switch back to `python-constraint`
  .constraints/py3.10.txt
  .constraints/py3.11.txt
  .constraints/py3.12.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  pyproject.toml
Labels: 🐛 Bug

#289 DX: define developer environment with `uv`
  .binder/apt.txt
  .binder/postBuild
  .binder/runtime.txt
  .constraints/.gitignore
  .constraints/py3.10.txt
  .constraints/py3.11.txt
  .constraints/py3.12.txt
  .constraints/py3.9.txt
  .cspell.json
  .editorconfig
  .envrc
  .gitattributes
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/clean-caches.yml
  .github/workflows/lock.yml
  .github/workflows/pr-linting.yml
  .github/workflows/release-drafter.yml
  .gitignore
  .pre-commit-config.yaml
  .python-version
  .readthedocs.yml
  .vscode/settings.json
  CONTRIBUTING.md
  README.md
  docs/conf.py
  docs/index.md
  docs/install.md
  environment.yml
  pyproject.toml
  tox.ini
  uv.lock
Labels: 🔨 Maintenance, 🖱️ DX

#292 MAINT: have `qn_domains`-keys in Node/EdgeSettings be typed
  docs/conf.py
  src/qrules/quantum_numbers.py
  src/qrules/solving.py
Labels: 🔨 Maintenance

#299 FIX: define dev dependencies as dependency groups
  .binder/postBuild
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  CONTRIBUTING.md
  docs/install.md
  pyproject.toml
  src/qrules/transition.py
  uv.lock
Labels: 🔨 Maintenance, 🖱️ DX, ⚠️ Interface
