Repository ComPWA/qrules, pull requests merged in 2024-12, with the labels that each got.

#288 ENH: use `Fraction` for spin values
  docs/conf.py
  src/qrules/__init__.py
  src/qrules/argument_handling.py
  src/qrules/combinatorics.py
  src/qrules/conservation_rules.py
  src/qrules/io/_dict.py
  src/qrules/io/_dot.py
  src/qrules/particle.py
  src/qrules/quantum_numbers.py
  src/qrules/settings.py
  src/qrules/system_control.py
  src/qrules/transition.py
  tests/unit/conservation_rules/test_c_parity.py
  tests/unit/conservation_rules/test_clebsch_gordan.py
  tests/unit/conservation_rules/test_g_parity.py
  tests/unit/conservation_rules/test_gellmann_nishijima.py
  tests/unit/conservation_rules/test_parity_conservation.py
  tests/unit/conservation_rules/test_spin.py
  tests/unit/test_particle.py
  tests/unit/test_quantum_numbers.py
  tests/unit/test_settings.py
  tests/unit/test_system_control.py
  tests/unit/test_transition.py
Labels: ⚙️ Enhancement

#313 FIX: support `QNProblemSet` in `asdot()`
  .cspell.json
  .vscode/settings.json
  docs/usage/visualize.ipynb
  src/qrules/io/_dot.py
  tests/unit/io/test_dot.py
Labels: 🐛 Bug

#311 MAINT: update lock files
  .cspell.json
  .envrc
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  pyproject.toml
  src/qrules/io/_dot.py
  src/qrules/particle.py
  uv.lock
Labels: 🔨 Maintenance

#310 ENH: implement `FrozenDict` with `frozendict`
  docs/conf.py
  pyproject.toml
  src/qrules/topology.py
  tests/unit/test_topology.py
  tests/unit/test_transition.py
  uv.lock
Labels: ⚙️ Enhancement

#314 MAINT: update `qrules` tag in `uv.lock`
  uv.lock
Labels: 🔨 Maintenance
